### Задание 1
П.1

In [83]:
import numpy as np

In [84]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [85]:
a1 = a.reshape(2,6)
a2 = a.reshape(3,4)
a3 = a.reshape(4,3)
a4 = a.reshape(6,2)
a5 = a.reshape(12,1)
print(a1)
print()
print(a2)
print()
print(a3)
print()
print(a4)
print()
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [86]:
a1 = a.reshape(2, -1)
a1 = a.reshape(3, -1)
a1 = a.reshape(4, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)
print(a1)
print()
print(a2)
print()
print(a3)
print()
print(a4)
print()
print(a5)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Массив Numpy, состоящий из одного столбца и 12 строк, нельзя назвать одномерным.

П.2

In [87]:
b = np.random.randn(3, 4)
print(b)
a.size

[[ 0.07983181 -0.1595165   0.02222183 -0.42779291]
 [-0.53181741 -0.1174755   0.2220789  -0.7679765 ]
 [ 0.1424646  -0.03465218  1.13433927 -0.10474555]]


12

In [88]:
c = b.flatten()
print(c)

[ 0.07983181 -0.1595165   0.02222183 -0.42779291 -0.53181741 -0.1174755
  0.2220789  -0.7679765   0.1424646  -0.03465218  1.13433927 -0.10474555]


П.3

In [89]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [90]:
a.shape

(10,)

In [91]:
b = np.arange(20,1,-2).reshape(1,-1)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


In [92]:
b.shape

(1, 10)

Разница в размерности.

П.4

In [93]:
num = 2
a = np.zeros((2, num))
print(a)
b = np.ones((num+1, num))
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [94]:
c = np.vstack((a, b))
print(c)
c.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

П.5

In [95]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [96]:
A = a.reshape(4, 3)
print(A)
print()
At = A.T
print(At)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [97]:
B = A @ At
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


Матрица B имеет размер 4х4. 

In [98]:
print(np.linalg.det(B))

0.0


Обратную матрицу не можем посчитать, потому что определитель равен нулю.

П.6

In [99]:
np.random.seed(42)

In [100]:
a = np.random.randint(0, 16, 16)
print(a)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


In [101]:
C = a.reshape(4, 4)
print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [102]:
D = B + (C*10)
print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [103]:
d = np.linalg.det(D)
print(d)

-28511999.999999944


In [104]:
r = np.linalg.matrix_rank(D)
print(r)

4


In [105]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [106]:
D_inv[D_inv < 0] = 0

In [107]:
D_inv[D_inv != 0] = 1

In [108]:
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [109]:
E = np.where(D_inv, B, C)

In [110]:
print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]


### Задание 2


In [111]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [112]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [113]:
a.shape

(5, 2)

In [114]:
mean_a = np.mean(a,0)

In [115]:
print(mean_a)

[2.  8.4]


### Задание 3

In [116]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### Задание 4

In [117]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
print(a_centered_sp)

8.0


In [118]:
r = a_centered_sp/(a_centered.shape[0]-1)
print(r)

2.0


### Задание 5

In [119]:
R = np.cov(a.T)
print(R)

[[1.  2. ]
 [2.  4.3]]


In [120]:
r == R[0,1]

True